project_id = "qvhgivhlgumcxaneizzb"

[functions.extract-document]
verify_jwt = false

[functions.extract-insurance-policy]
verify_jwt = false

[functions.review-insurance-policy]
verify_jwt = false

[functions.driver-onboarding]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false