// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-vehicles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vehicles_default = defineTool({
  name: "list_vehicles",
  title: "Listar ve\xEDculos",
  description: "Lista os ve\xEDculos da frota do usu\xE1rio autenticado (respeita permiss\xF5es da empresa).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de ve\xEDculos a retornar."),
    status: z.string().optional().describe("Filtrar por status (ex.: 'ativo', 'inativo', 'vendido')."),
    search: z.string().optional().describe("Busca por placa, marca ou modelo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("vehicles").select(
      "id, plate, brand, model, year_model, color, status, current_km, fuel_type, licensing_year, chassis, renavam"
    ).order("plate", { ascending: true }).limit(limit);
    if (status) q = q.eq("status", status);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`plate.ilike.${s},brand.ilike.${s},model.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { vehicles: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-drivers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient2(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_drivers_default = defineTool2({
  name: "list_drivers",
  title: "Listar motoristas",
  description: "Lista os motoristas cadastrados na empresa do usu\xE1rio autenticado.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50),
    search: z2.string().optional().describe("Busca por nome ou CPF.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("drivers").select("id, full_name, cpf, cnh, cnh_category, cnh_expires_at, phone, email, status").order("full_name", { ascending: true }).limit(limit);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`full_name.ilike.${s},cpf.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { drivers: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-company.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient3(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_company_default = defineTool3({
  name: "get_company",
  title: "Obter dados da empresa",
  description: "Retorna dados da empresa atual do usu\xE1rio autenticado (nome, CNPJ, endere\xE7o, contato).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: profile, error: pErr } = await sb.from("profiles").select("current_company_id").eq("id", ctx.getUserId()).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const companyId = profile?.current_company_id;
    if (!companyId) {
      return {
        content: [{ type: "text", text: "Usu\xE1rio n\xE3o tem empresa atual selecionada." }],
        isError: true
      };
    }
    const { data, error } = await sb.from("companies").select(
      "id, name, cnpj, email, phone, contact_name, cep, address, address_number, neighborhood, city, state, status"
    ).eq("id", companyId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { company: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qvhgivhlgumcxaneizzb";
var mcp_default = defineMcp({
  name: "frotaops-mcp",
  title: "FrotaOps MCP",
  version: "0.1.0",
  instructions: "Ferramentas do FrotaOps: consulte a empresa do usu\xE1rio, ve\xEDculos e motoristas da frota. Use `get_company` para dados cadastrais, `list_vehicles` para a frota e `list_drivers` para motoristas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_company_default, list_vehicles_default, list_drivers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
